config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home" => "pages#hello"
  get "/webdesign" => "pages#webdesign"

  get "/android"  => "pages#android"
  get "/laravel"  => "pages#laravel"
  get "/nodecourse"  => "pages#nodecourse"
  get "/diploma"  => "pages#diploma"
  get "/hnd"   => "pages#hnd"
   
  get "rail" => "pages#rail"
  get "/bscweb"   => "pages#bscweb"
  get "/graphics"   => "pages#graphics"
  get "/bscmobile"   => "pages#bscmobile"
   
  get "/bscsoftware"  => "pages#bscsoftware"
  get "/bsccsna"  => "pages#bsccsna"
  get "/bscce" => "pages#bscce"
  get "/bscgmm" => "pages#bscgmm"
  get "/bscccbd" => "pages#bscccbd"
  get "/bscsecure" => "pages#bscsecure"
  resources :users , except: [:update, :destroy]


  root 'pages#hello'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :user_courses
	has_many :users, through: :user_courses

	
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :confirmation_token, :reset_token

  has_many :user_courses, dependent: :destroy
  has_many :courses, through: :user_courses

  before_save :downcase_email
  before_create :create_confirmation_digest
  
  
  
  
  validates :qualification,  presence: { message: "Pls fill your qualification"}
  validates :phone,  presence: { message: "give us your phone number"}
  validates :family_name,  presence: { message: "Family name please"}
  validates :other_names,  presence: { message: "Other names please"}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: { message: "email must be filled"},
                    format: { with: VALID_EMAIL_REGEX, message: ", email invalid" },
                    uniqueness: { case_sensitive: false, message: "email already in use." }

  has_secure_password

  validates :password, presence: {message: "must be filled"}, on: :create, length: { minimum: 6, message: "Password must be at least 6 letters"}, allow_nil: true
  validates :course_ids,  presence: { message: "Select your course"} 
    #used to create the digest of any string
  def self.digest(string) 
    BCrypt::Password.create(string, cost: 8)
  end

  # use this to generate any random url safe base64 token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  #this method sets a remeber_token then inserts its digest in the remember_column of a user 
  def remember
    self.remember_token = User.new_token  
    update_attribute(:remember_digest, User.digest(remember_token))  
  end

  #this generalised method checks whether the token your provide corresponds to the digest stored. if there is a mismatch it return false
  #the digest.nil? part is crucial for those who sign in many diiferent browsers on the same machine. 
  # imagine user signs out in firefox, close one chrome browser then tries to use the last browser to request unauthorized pages.

  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?                        
                                                         
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # create and sets a reset_digest, reset_token virtual attribute a
  def create_reset_digest
      self.reset_token = User.new_token
      update_attribute(:reset_digest,  User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

 

  private

   # Converts email to all lower-case.
    def downcase_email
       self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_confirmation_digest
      self.confirmation_token  = User.new_token
      self.confirmation_digest = User.digest(confirmation_token)
    end

    
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def hello 
  end

  def webdesign
    @page_title = "Web Design Certificate"
  end

  def android
    @page_title = "Android App Development Certificate"
  end

  def bscsecure
    @page_title = "Bsc in Cyber Security"
  end

  def laravel
    @page_title = "Laravel Course Certificate"
  end

  def graphics
    @page_title = "Graphics Design Diploma"
  end

  def nodecourse
    @page_title = "Node Course Certificate"
  end

  def diploma
    @page_title = "Professional Diploma in Web and Android Systems"
  end

  def hnd
    @page_title = "HND in Software Engineering"
  end

  def bscmobile
    @page_title = "BSc in Mobile Computing"
  end

  def bscweb
    @page_title = "Bsc in Web and Mobile Systems"
  end
  
  def rail
    @page_title = "Ruby on Rails Certificate"
  end 

  def bscsoftware
    @page_title = "Bsc in Software Engineering"
  end

  def bsccsna
    @page_title = "Bsc computer systems and Network Administration"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new()
    @courses = Course.all
  end

  def create
    @user= User.new(user_params)
    @courses = Course.all
    
    if @user.save  
      flash[:success]= "Thank You. Your Application has been received. Meet us on campus"
      redirect_to diploma_path
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  private

  def user_params
     params.require(:user).permit(:family_name, :other_names, :email, :password_confirmation, :password, :phone, :qualification, :nationality, :course_ids)
   end
    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_message.html.erb
<div class="container message-div" >
    <% flash.each do |key, msg| %>
    <div class=" alert alert-<%= key %>">
      <a class="close" data-dismiss='alert'> &#215;</a>
      <%= content_tag :div, msg %>
    </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

    <head>
        <title><%= @page_title %></title>
        <%= csrf_meta_tags %>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
         <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>  
          <%= favicon_link_tag 'pages/iipawislogo.png' %>
          <!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
 fbq('init', '633353003782763'); 
fbq('track', 'PageView');
<% if @page_title == 'Apply for admission' %>
  fbq('track', 'SubmitApplication');
<% end %>
fbq('track', 'ViewContent');
</script>
<noscript>
 <img height="1" width="1" 
src="https://www.facebook.com/tr?id=633353003782763&ev=PageView
&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->
         <style type="text/css">
         @import url("https://fonts.googleapis.com/css?family=Open+Sans:400,600,700|Raleway:500,600,700");
          .register-button {
   
              background: #0066cc;
              border: 1px solid #f1f1f1;
              font-size: 20px;
              font-weight: 100;
              letter-spacing: 2px;
              color: #fff;
              
            }
            .mobile-content h3 {
              color: #fff;
              margin-bottom: 40px;
              font-weight: 600
            }

             .android {
              
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/androidapp.jpg); 
            }
            .webdesign {
              /*background-image: url(pages/androidapp.jpg); */
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/frontend.jpg);
            }

             

            .it{
  
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/itpic2.jpg); 
            }
         .gmm{ 
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/gmm.jpg); 
            }

             .ce{  
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/ceng.jpg); 
            }
             
             .webdev{
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/webdev.jpg); 
            }

            .ccbd{  
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/bigdata.png); 
            }

            .secure{  
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/secure/jpg); 
            }
             
             

            .software {
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/software.jpg);
            }


            .php {
              
              /*background-image: url(pages/androidapp.jpg); */
              background: linear-gradient(rgba(0, 0, 0, 0.9), rgba(0, 0, 0, 0.4)), url(assets/pages/phone2.jpg);
            }

            .register-button:hover {
              background: #0066cc;
            }
            .new-user-wrapper { 
              padding: 1px;
              
              
              border: 1px solid #aaaaaa;
             padding-top: 0px;
              margin-top: 50px
            }
             .grey-text {
              margin-top: 17px;
              color: #a9640e;
              font-size: 17px;
              font-weight: 100

             }

             .dta {font-weight: 300!important;}
             

            .title {
              margin-bottom: 30px;
            }
            .error-span {
              color: red;
            }
            .short {
              text-align: left;
            }

            .certificates h4 {
              text-align: left;
            }

            @media (max-width: 600px) {
              .new-user-wrapper {
                margin: 0 auto;
              }

              #mobile-div {
              overflow: auto;
            }
            .about {
              padding-top: 5px
            }
            }

            .dinfo {font-weight: 300; color: red;}

            .infos{
              font-size: 18px;
              color: #666;
            } 

            .registerform {
              background: #f1f1f1;
              border-radius: 0px;
              margin: 0;
              margin-bottom: -1px;
            }

            
            /* ----------login page--------------- */

            .login-form { 
            background-color: #fff;
            margin-top: 50px;
            border: 1px solid #aaaaaa;
            }
            /* ----------some front page styles--------------- */

            .course-intro h4 {
                margin-top: 33px;
                color: #e43a3a;
                font-weight: 600;
            }

            .message-div {
                position:fixed; 
                top: 70px; 
                left: 0px; 
                width: 100%;
                z-index:9999; 
                border-radius:0px;   
            }
            
            .btn-info {
  padding:10px 18px;
  background-color: #d9d9d9;
  color: #2098d1;
  border: 3px solid #2098d1;
  border-radius: 300px;
  font-size: 22px;
  margin-bottom: 10px;
}
.diploma-instruct {
  color: red;
  font-weight: 300;
}

.course .item {
  border: 1px solid #aaa;
  border-radius: 0;

}

.title-line {
  border-bottom: 2px solid #000;
  width: 70%;
  margin: 0 0;
}

.top-bar {border-bottom: 1px solid #ccc; border-top: 1px solid #ccc;}
         </style>
    </head>


  

  <body>
  	<div class="toppanel">
      <div class="container showcase">
        <%= link_to root_path do %>
          <div class="logo col-md-2 col-md-offset-0 col-xs-6 col-xs-offset-3">
           <%= image_tag('pages/iipawislogo.png', class: 'img-responsive') %> 
          </div>
        <% end %>
                
        <div class="col-md-10 col-xs-12">
          <%= link_to 'Apply Here', new_user_path, class: "btn btn-info btn-lg pull-right hidden-xs hidden-sm" %>
            <h4 class="page-title ">International Institute for Professional Android, Web and IT Systems</h4>
            
            <div class="h-bar hidden-lg hidden-md" ><i class="fa fa-book"></i></div>
            <h5>RAISING TECH GURUS</h5>                   
        </div>
      </div>
    </div>
         
        <!--<div class="grad col-sm-12"></div>-->
       <%= render 'layouts/message' %>
    <%= yield %>

    
    
  </body>
</html>

app/views/pages/_bottomcoursedetails.html.erb
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <!-- Sidebar Container Start -->
                        <div class="sidebar">  
                        <br><br><br><br><br><br><br><br>                        
                            <div class="widget">
                                <h4>Our Programs</h4>
                                
                                <h5>Professional Diploma courses (click on a course) </h5>
                                <ul>
                                    <li><%= link_to "Professional Diploma in Android and Web systems", diploma_path %></li>
                                    <li><%= link_to "Professional Diploma in Graphics Design", graphics_path %></li>
                                </ul>
                                <h5>Professional Bachelors (click on a course) </h5>
                                <ul>
                                    <li><%= link_to "Bsc in Web and Mobile Systems", bscweb_path %></li>
                                    <li><%= link_to "Bsc in Mobile Computing", bscmobile_path %></li>
                                    <li><%= link_to "Bsc in Computer Software Engineering", bscsoftware_path %></li>
                                    <li><%= link_to "Bsc in Computer Systems and Network Administration", bsccsna_path %></li>
                                    <li><%= link_to "Bsc in Computer Engineering", bscce_path %></li>
                                    <li><%= link_to "Bsc in Graphics Design and Multimedia", bscgmm_path %></li>
                                    <li><%= link_to "Bsc in Cloud Computing and Big Data", bscccbd_path %></li>
                                    
                                    
                                </ul>
                                <h5>Our HND Courses (click on a course)</h5>
                                <ul>
                                  <li><%= link_to "HND in Software Engineering and Computing", hnd_path %> </li>
                                     
                                </ul>
                                
                                <h5>Our Certificates short courses (click on a course)</h5>
                                <ul>
                                  <li><%= link_to "Android App Development", android_path %> </li>
                                  <li><%= link_to "Professional Mobile First Web Design", webdesign_path %> </li>
                                  <li><%= link_to "Web Development With PHP and Laravel", laravel_path %> </li>
                                  <li><%= link_to "Web Development with Node, Express and MongoDB", nodecourse_path %> </li> 
                                  <li><%= link_to "Web Development with Ruby on Rails", rail_path %> </li>   
                                </ul> 
                            </div>
                        </div>
                        <!-- Sidebar Container End -->
                    </div>
                </div>
            </div> 
        </section>   

app/views/pages/_bscgmmlist.html.erb
<h3>Professional BSc in Graphics Design and Multimedia</h3>
                                            <p class="dta"> We often wonder how those beautiful graphics displayed on TV when the news is about to start or during adverts are created. When we walk beside the road we see again complex graphics design sign boards or road banners. You may have also seen the computer models of houses, stadiums- or halls posted at the site before they are being constructed.<br>This bachelor degree program will equip you with the latest tools to acomplish complex infographics, graphics design as well use the computer to model architectural designs and much more.
                                            </p>
                                           
                                            <h4>Admission conditions:</strong></h4>
                                            <div>
                                            <span class="dinfo"> 
                                            A levels, BAC </span>
                                          </div>
                                            <br>
                                            <div class="well">
                                              <h4>Course Outline</h4>
                                              <p class="dta">Detailed course content is available from the department of Computer Science and Engineering or the director's office</p>
                                              
                                             </div>
                                            
                                             <h4>Course Details</h4>
                                             <table class="table table-striped table-bordered dta">
                                                <tbody>
                                                   <tr>
                                                        <th>Language of Instruction</th>
                                                        <td>English ( English course for non-English speakers)</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Course Start Date</th>
                                                        <td>Oct. 2019</td>
                                                    </tr>
                                                    
                                                    <tr>
                                                        <th>Estimated Duration</th>
                                                        <td> 3 Years</td>
                                                    </tr>
                                                    
                                                    <tr>
                                                        <th>Fees (per year)</th>
                                                        <td>CFA 500 000 (Cameroonians), <br> CFA 730,000 (Foreign Students) <br>Pay in 3 installments<br> Registration Fee: CFA 20,000 frs</td>
                                                    </tr>
                                                </tbody>
                                             </table>

app/views/pages/_bscmobilelist.html.erb
<h3>Professional BSc in Mobile Computing </h3>
                                            <p class="dta">Mobile computing involves mobile communication, mobile hardware, and mobile software. <br>Communication issues include ad hoc networks and infrastructure networks as well as communication properties, protocols, data formats and concrete technologies.<br> Hardware includes mobile devices and components. <br>Mobile software deals with mobile operating systems(Android, iOS and Windows) and how to develop applications on them.</p>
                                            <p>The mobile computing graduate is therefore skillful in software development for Windows, Android and iOS operating systems; Wireless communication, Mobile communication; and mobile device hardware maintenance</p>
                                             
                                           
                                            <p class="dta">Telecom companies, Banks, Mobile money institutions and start-ups clamour for our graduates </p>
                                            <h4>Admission conditions:</strong></h4>
                                            <div>
                                            <span class="dinfo"> 
                                             A levels, Bac </span>
                                          </div>
                                            <br>
                                            <div class="well">
                                              <h4>Course Outline</h4>
                                              <p class="dta">Detailed course content is available from the department of Web and Mobile systems or the director's office</p>
                                              
                                             </div>
                                            
                                             <h4>Course Details</h4>
                                             <table class="table table-striped table-bordered dta">
                                                <tbody>
                                                  <tr>
                                                        <th>Language of Instruction</th>
                                                        <td>English ( English course for non-English speakers)</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Course Start Date</th>
                                                        <td>Oct. 2019</td>
                                                    </tr>
                                                    
                                                    <tr>
                                                        <th>Estimated Duration</th>
                                                        <td> 3 Years</td>
                                                    </tr>
                                                    
                                                    <tr>
                                                        <th>Fees (per year)</th>
                                                        <td>CFA 500 000 (Cameroonians), <br> CFA 730,000 (Foreign Students) <br>Pay in 3 installments <br>Registration Fee: CFA 20, 000 frs</td>
                                                    </tr>
                                                </tbody>
                                             </table>

app/views/pages/_bscsecurelist.html.erb
<h3>Professional BSc in Cyber Security </h3>
                                            <p class="dta">Cyber security refers to the body of technologies, processes, and practices designed to protect networks, devices, programs, and data from attack, damage, or unauthorized access. Cyber security may also be referred to as information technology security

                                            Our BSc in Cyber Security trains students on the latest techniques of securing web and mobile applications, networks, computing systems and databases. The first and second years of studies give the student a solid foundation in professional web technologies, databases, computer systems, networking and advanced programming. The last year is the specialization year and includes courses on Ethical hacking and penetration testing, cryptography, server management and security, network security, etc.  </p>
                                           
                                            <p class="dta">Graduates in Cyber security can work as Security Consultant, Information Security Analyst, Ethical Hackers, Computer Forensics Analysts, Chief Information Security Officer, Penetration Tester, IT Security Consultant. Security Systems Administrator</p>
                                            <h4>Admission conditions:</strong></h4>
                                            <div>
                                            <span class="dinfo"> 
                                             A levels, Bac </span>
                                          </div>
                                            <br>
                                            <div class="well">
                                              <h4>Course Outline</h4>
                                              <p class="dta">Detailed course content is available from the director's office</p>
                                              
                                             </div>
                                            
                                             <h4>Course Details</h4>
                                             <table class="table table-striped table-bordered dta">
                                                <tbody>
                                                  <tr>
                                                        <th>Language of Instruction</th>
                                                        <td>English ( English course for non-English speakers)</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Course Start Date</th>
                                                        <td>Oct. 2019</td>
                                                    </tr>
                                                    
                                                    <tr>
                                                        <th>Estimated Duration</th>
                                                        <td> 3 Years</td>
                                                    </tr>
                                                    
                                                    <tr>
                                                        <th>Fees (per year)</th>
                                                        <td>CFA 500 000 (Cameroonians), <br> CFA 730,000 (Foreign Students) <br>Pay in 3 installments <br>Registration Fee: CFA 20, 000 frs</td>
                                                    </tr>
                                                </tbody>
                                             </table>

app/views/pages/_bscweblist.html.erb
                                            <h3>Professional BSc in Web and Mobile Systems </h3>
                                            <p class="dta">Web development is the application of software engineering principles to the development of complex intranet or internet systems. This program takes students through mobile first responsive web design; web content development; client-side/server-side scripting; network system configuration, security and administration; cloud computing; SQL/NoSQL database technologies and tools to design, develop, and deploy networked apps on mobile operating systems</p>
                                            <p>Graduates of this program will be able to program in HTML5, CSS3/Less/SASS, Javascript/ES2017, Java/Kotlin, Php 7, Python, Node,  C#, C/C++ as well as understand how to use frameworks( Laravel, Express, Bootstrap, React, Jquery, Angularjs, Vuejs, Django, Flask and Java Spring/Play) </p>
                                            <h4>Admission conditions:</strong></h4>
                                            <div>
                                            <span class="dinfo"> 
                                            A levels, BAC or <br> Top-up options exists for BTS, and HND graduate in Software engineering and computing </span>
                                          </div>
                                            <br>
                                            <div class="well">
                                              <h4>Course Outline</h4>
                                              <p class="dta">Detailed course content is available from the department of Web and Mobile systems or the director's office</p>
                                              
                                             </div>
                                            
                                             <h4>Course Details</h4>
                                             <table class="table table-striped table-bordered dta">
                                                <tbody>
                                                  <tr>
                                                        <th>Language of Instruction</th>
                                                        <td>English ( English course for non-English speakers)</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Course Start Date</th>
                                                        <td>18th March, 2019</td>
                                                    </tr>
                                                    
                                                    <tr>
                                                        <th>Estimated Duration</th>
                                                        <td> 3 Years</td>
                                                    </tr>
                                                    
                                                    <tr>
                                                        <th>Fees (per year)</th>
                                                        <td>CFA 500 000 (Cameroonians), <br> CFA 730,000 (Foreign Students) <br>Pay in 3 installments <br>Registration Fee: CFA 20, 000 frs</td>
                                                    </tr>
                                                </tbody>
                                             </table>

app/views/pages/android.html.erb
<!-- course detail top --> 
        <%= render 'topcoursedetails' %>
        <!-- coursedetailtop ends here -->

                                        <!--courseproper -->
                                        <div class="text no-pb">
                                            <%= render 'androidlist' %>
                                        </div>
                                    <!--courseproper ends here-->
 <!--bottom coursedetails -->
<%= render 'bottomcoursedetails' %>
<!--bottom coursedetails ends here -->
        
        <!-- footer -->
<%= render 'footer' %>
        <!--footer ends here -->